### ISSUE TITLE
fix spelling - plural of potato 

### ISSUE THREAD

**Issue by dmil** [dmil/my-simple-website#27]
How do you spell that word again?

![image](https://user-images.githubusercontent.com/468544/101135664-1b2cde00-35da-11eb-99b3-270f71bd2d39.png)

**Comment by harikarayala** [comment]
Very difficult question. It is "potatoes."

**Comment by dmil** [comment]
Ah, thanks! Glad I asked. I thought it was "potatos". I'm fixing that now.
