### ISSUE TITLE
Add pizzaz

### ISSUE THREAD

**Issue by dmil** [dmil/my-simple-website#4]
Can someone who already knows how to code handle this ticket? Maybe turn the headline into a [marquee](https://www.tutorialspoint.com/html/html_marquees) or some other bizzaro thing to make this boring old website a little funkier? 

Please make sure it is a simple one-line change.

**Comment by juruwolfe** [comment]
I'm obviously going with marquee

**Comment by colleenbarry** [comment]
I think there should be glitter and maybe blinking text

**Comment by KaleighRogers** [comment]
How about a cursor trail? Geocities style

**Comment by lbronner** [comment]
Agree with @colleenbarry !

**Comment by juruwolfe** [comment]
Ooh good point. Let me amend the branch so it brings a little more magic

**Comment by juruwolfe** [comment]
No fun cursor trails or text for times sake, but i DID make it curly font and PIIIIINKKK. Check out #29
